#[derive(Copy, Clone, Debug)]
pub enum AddressingMode {
    Implied,
    Accumulator,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Relative,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndexedIndirect,
    IndirectIndexed,
}

static ADDRESSING_MODE_MAP: &'static[AddressingMode] = &[
  AddressingMode::Implied   , AddressingMode::IndexedIndirect , AddressingMode::Implied     , AddressingMode::IndexedIndirect ,
  AddressingMode::ZeroPage  , AddressingMode::ZeroPage        , AddressingMode::ZeroPage    , AddressingMode::ZeroPage        ,
  AddressingMode::Implied   , AddressingMode::Immediate       , AddressingMode::Accumulator , AddressingMode::Immediate       ,
  AddressingMode::Absolute  , AddressingMode::Absolute        , AddressingMode::Absolute    , AddressingMode::Absolute        ,
  AddressingMode::Relative  , AddressingMode::IndirectIndexed , AddressingMode::Implied     , AddressingMode::IndirectIndexed ,
  AddressingMode::ZeroPageX , AddressingMode::ZeroPageX       , AddressingMode::ZeroPageX   , AddressingMode::ZeroPageX       ,
  AddressingMode::Implied   , AddressingMode::AbsoluteY       , AddressingMode::Implied     , AddressingMode::AbsoluteY       ,
  AddressingMode::AbsoluteX , AddressingMode::AbsoluteX       , AddressingMode::AbsoluteX   , AddressingMode::AbsoluteX       ,
  AddressingMode::Absolute  , AddressingMode::IndexedIndirect , AddressingMode::Implied     , AddressingMode::IndexedIndirect ,
  AddressingMode::ZeroPage  , AddressingMode::ZeroPage        , AddressingMode::ZeroPage    , AddressingMode::ZeroPage        ,
  AddressingMode::Implied   , AddressingMode::Immediate       , AddressingMode::Accumulator , AddressingMode::Immediate       ,
  AddressingMode::Absolute  , AddressingMode::Absolute        , AddressingMode::Absolute    , AddressingMode::Absolute        ,
  AddressingMode::Relative  , AddressingMode::IndirectIndexed , AddressingMode::Implied     , AddressingMode::IndirectIndexed ,
  AddressingMode::ZeroPageX , AddressingMode::ZeroPageX       , AddressingMode::ZeroPageX   , AddressingMode::ZeroPageX       ,
  AddressingMode::Implied   , AddressingMode::AbsoluteY       , AddressingMode::Implied     , AddressingMode::AbsoluteY       ,
  AddressingMode::AbsoluteX , AddressingMode::AbsoluteX       , AddressingMode::AbsoluteX   , AddressingMode::AbsoluteX       ,
  AddressingMode::Implied   , AddressingMode::IndexedIndirect , AddressingMode::Implied     , AddressingMode::IndexedIndirect ,
  AddressingMode::ZeroPage  , AddressingMode::ZeroPage        , AddressingMode::ZeroPage    , AddressingMode::ZeroPage        ,
  AddressingMode::Implied   , AddressingMode::Immediate       , AddressingMode::Accumulator , AddressingMode::Immediate       ,
  AddressingMode::Absolute  , AddressingMode::Absolute        , AddressingMode::Absolute    , AddressingMode::Absolute        ,
  AddressingMode::Relative  , AddressingMode::IndirectIndexed , AddressingMode::Implied     , AddressingMode::IndirectIndexed ,
  AddressingMode::ZeroPageX , AddressingMode::ZeroPageX       , AddressingMode::ZeroPageX   , AddressingMode::ZeroPageX       ,
  AddressingMode::Implied   , AddressingMode::AbsoluteY       , AddressingMode::Implied     , AddressingMode::AbsoluteY       ,
  AddressingMode::AbsoluteX , AddressingMode::AbsoluteX       , AddressingMode::AbsoluteX   , AddressingMode::AbsoluteX       ,
  AddressingMode::Implied   , AddressingMode::IndexedIndirect , AddressingMode::Implied     , AddressingMode::IndexedIndirect ,
  AddressingMode::ZeroPage  , AddressingMode::ZeroPage        , AddressingMode::ZeroPage    , AddressingMode::ZeroPage        ,
  AddressingMode::Implied   , AddressingMode::Immediate       , AddressingMode::Accumulator , AddressingMode::Immediate       ,
  AddressingMode::Indirect  , AddressingMode::Absolute        , AddressingMode::Absolute    , AddressingMode::Absolute        ,
  AddressingMode::Relative  , AddressingMode::IndirectIndexed , AddressingMode::Implied     , AddressingMode::IndirectIndexed ,
  AddressingMode::ZeroPageX , AddressingMode::ZeroPageX       , AddressingMode::ZeroPageX   , AddressingMode::ZeroPageX       ,
  AddressingMode::Implied   , AddressingMode::AbsoluteY       , AddressingMode::Implied     , AddressingMode::AbsoluteY       ,
  AddressingMode::AbsoluteX , AddressingMode::AbsoluteX       , AddressingMode::AbsoluteX   , AddressingMode::AbsoluteX       ,
  AddressingMode::Immediate , AddressingMode::IndexedIndirect , AddressingMode::Immediate   , AddressingMode::IndexedIndirect ,
  AddressingMode::ZeroPage  , AddressingMode::ZeroPage        , AddressingMode::ZeroPage    , AddressingMode::ZeroPage        ,
  AddressingMode::Implied   , AddressingMode::Immediate       , AddressingMode::Implied     , AddressingMode::Immediate       ,
  AddressingMode::Absolute  , AddressingMode::Absolute        , AddressingMode::Absolute    , AddressingMode::Absolute        ,
  AddressingMode::Relative  , AddressingMode::IndirectIndexed , AddressingMode::Implied     , AddressingMode::IndirectIndexed ,
  AddressingMode::ZeroPageX , AddressingMode::ZeroPageX       , AddressingMode::ZeroPageY   , AddressingMode::ZeroPageY       ,
  AddressingMode::Implied   , AddressingMode::AbsoluteY       , AddressingMode::Implied     , AddressingMode::AbsoluteY       ,
  AddressingMode::AbsoluteX , AddressingMode::AbsoluteX       , AddressingMode::AbsoluteY   , AddressingMode::AbsoluteY       ,
  AddressingMode::Immediate , AddressingMode::IndexedIndirect , AddressingMode::Immediate   , AddressingMode::IndexedIndirect ,
  AddressingMode::ZeroPage  , AddressingMode::ZeroPage        , AddressingMode::ZeroPage    , AddressingMode::ZeroPage        ,
  AddressingMode::Implied   , AddressingMode::Immediate       , AddressingMode::Implied     , AddressingMode::Immediate       ,
  AddressingMode::Absolute  , AddressingMode::Absolute        , AddressingMode::Absolute    , AddressingMode::Absolute        ,
  AddressingMode::Relative  , AddressingMode::IndirectIndexed , AddressingMode::Implied     , AddressingMode::IndirectIndexed ,
  AddressingMode::ZeroPageX , AddressingMode::ZeroPageX       , AddressingMode::ZeroPageY   , AddressingMode::ZeroPageY       ,
  AddressingMode::Implied   , AddressingMode::AbsoluteY       , AddressingMode::Implied     , AddressingMode::AbsoluteY       ,
  AddressingMode::AbsoluteX , AddressingMode::AbsoluteX       , AddressingMode::AbsoluteY   , AddressingMode::AbsoluteY       ,
  AddressingMode::Immediate , AddressingMode::IndexedIndirect , AddressingMode::Immediate   , AddressingMode::IndexedIndirect ,
  AddressingMode::ZeroPage  , AddressingMode::ZeroPage        , AddressingMode::ZeroPage    , AddressingMode::ZeroPage        ,
  AddressingMode::Implied   , AddressingMode::Immediate       , AddressingMode::Implied     , AddressingMode::Immediate       ,
  AddressingMode::Absolute  , AddressingMode::Absolute        , AddressingMode::Absolute    , AddressingMode::Absolute        ,
  AddressingMode::Relative  , AddressingMode::IndirectIndexed , AddressingMode::Implied     , AddressingMode::IndirectIndexed ,
  AddressingMode::ZeroPageX , AddressingMode::ZeroPageX       , AddressingMode::ZeroPageX   , AddressingMode::ZeroPageX       ,
  AddressingMode::Implied   , AddressingMode::AbsoluteY       , AddressingMode::Implied     , AddressingMode::AbsoluteY       ,
  AddressingMode::AbsoluteX , AddressingMode::AbsoluteX       , AddressingMode::AbsoluteX   , AddressingMode::AbsoluteX       ,
  AddressingMode::Immediate , AddressingMode::IndexedIndirect , AddressingMode::Immediate   , AddressingMode::IndexedIndirect ,
  AddressingMode::ZeroPage  , AddressingMode::ZeroPage        , AddressingMode::ZeroPage    , AddressingMode::ZeroPage        ,
  AddressingMode::Implied   , AddressingMode::Immediate       , AddressingMode::Implied     , AddressingMode::Immediate       ,
  AddressingMode::Absolute  , AddressingMode::Absolute        , AddressingMode::Absolute    , AddressingMode::Absolute        ,
  AddressingMode::Relative  , AddressingMode::IndirectIndexed , AddressingMode::Implied     , AddressingMode::IndirectIndexed ,
  AddressingMode::ZeroPageX , AddressingMode::ZeroPageX       , AddressingMode::ZeroPageX   , AddressingMode::ZeroPageX       ,
  AddressingMode::Implied   , AddressingMode::AbsoluteY       , AddressingMode::Implied     , AddressingMode::AbsoluteY       ,
  AddressingMode::AbsoluteX , AddressingMode::AbsoluteX       , AddressingMode::AbsoluteX   , AddressingMode::AbsoluteX       ,
];

impl AddressingMode {
    pub fn bytes(self) -> u8 {
        match self {
            AddressingMode::Implied => 0,
            AddressingMode::Accumulator => 0,
            AddressingMode::Immediate => 1,
            AddressingMode::ZeroPage => 1,
            AddressingMode::ZeroPageX => 1,
            AddressingMode::ZeroPageY => 1,
            AddressingMode::Relative => 1,
            AddressingMode::Absolute => 2,
            AddressingMode::AbsoluteX => 2,
            AddressingMode::AbsoluteY => 2,
            AddressingMode::Indirect => 2,
            AddressingMode::IndexedIndirect => 1,
            AddressingMode::IndirectIndexed => 1,
        }
    }
}

impl From<u8> for AddressingMode {
    fn from(opcode: u8) -> Self {
        ADDRESSING_MODE_MAP[opcode as usize]
    }
}

#[derive(Copy, Clone, Debug)]
pub enum Instruction {
    LDA, LDX, LDY, STA, STX, STY, TAX, TAY,
    TXA, TYA, TSX, TXS, PHA, PHP, PLA, PLP,
    AND, EOR, ORA, BIT, ADC, SBC, CMP, CPX,
    CPY, INC, INX, INY, DEC, DEX, DEY, ASL,
    LSR, ROL, ROR, JMP, JSR, RTS, BCC, BCS,
    BEQ, BMI, BNE, BPL, BVC, BVS, CLC, CLD,
    CLI, CLV, SEC, SED, SEI, BRK, NOP, RTI,

    /* Unofficial instructions */
    AHX, ALR, ANC, ARR, AXS, DCP, ISC, LAS,
    LAX, RLA, RRA, SAX, SHX, SHY, SLO, SRE,
    STP, TAS, XAA,
}

static INSTRUCTION_MAP: &'static[Instruction] = &[
    Instruction::BRK, Instruction::ORA, Instruction::STP, Instruction::SLO,
    Instruction::NOP, Instruction::ORA, Instruction::ASL, Instruction::SLO,
    Instruction::PHP, Instruction::ORA, Instruction::ASL, Instruction::ANC,
    Instruction::NOP, Instruction::ORA, Instruction::ASL, Instruction::SLO,
    Instruction::BPL, Instruction::ORA, Instruction::STP, Instruction::SLO,
    Instruction::NOP, Instruction::ORA, Instruction::ASL, Instruction::SLO,
    Instruction::CLC, Instruction::ORA, Instruction::NOP, Instruction::SLO,
    Instruction::NOP, Instruction::ORA, Instruction::ASL, Instruction::SLO,
    Instruction::JSR, Instruction::AND, Instruction::STP, Instruction::RLA,
    Instruction::BIT, Instruction::AND, Instruction::ROL, Instruction::RLA,
    Instruction::PLP, Instruction::AND, Instruction::ROL, Instruction::ANC,
    Instruction::BIT, Instruction::AND, Instruction::ROL, Instruction::RLA,
    Instruction::BMI, Instruction::AND, Instruction::STP, Instruction::RLA,
    Instruction::NOP, Instruction::AND, Instruction::ROL, Instruction::RLA,
    Instruction::SEC, Instruction::AND, Instruction::NOP, Instruction::RLA,
    Instruction::NOP, Instruction::AND, Instruction::ROL, Instruction::RLA,
    Instruction::RTI, Instruction::EOR, Instruction::STP, Instruction::SRE,
    Instruction::NOP, Instruction::EOR, Instruction::LSR, Instruction::SRE,
    Instruction::PHA, Instruction::EOR, Instruction::LSR, Instruction::ALR,
    Instruction::JMP, Instruction::EOR, Instruction::LSR, Instruction::SRE,
    Instruction::BVC, Instruction::EOR, Instruction::STP, Instruction::SRE,
    Instruction::NOP, Instruction::EOR, Instruction::LSR, Instruction::SRE,
    Instruction::CLI, Instruction::EOR, Instruction::NOP, Instruction::SRE,
    Instruction::NOP, Instruction::EOR, Instruction::LSR, Instruction::SRE,
    Instruction::RTS, Instruction::ADC, Instruction::STP, Instruction::RRA,
    Instruction::NOP, Instruction::ADC, Instruction::ROR, Instruction::RRA,
    Instruction::PLA, Instruction::ADC, Instruction::ROR, Instruction::ARR,
    Instruction::JMP, Instruction::ADC, Instruction::ROR, Instruction::RRA,
    Instruction::BVS, Instruction::ADC, Instruction::STP, Instruction::RRA,
    Instruction::NOP, Instruction::ADC, Instruction::ROR, Instruction::RRA,
    Instruction::SEI, Instruction::ADC, Instruction::NOP, Instruction::RRA,
    Instruction::NOP, Instruction::ADC, Instruction::ROR, Instruction::RRA,
    Instruction::NOP, Instruction::STA, Instruction::NOP, Instruction::SAX,
    Instruction::STY, Instruction::STA, Instruction::STX, Instruction::SAX,
    Instruction::DEY, Instruction::NOP, Instruction::TXA, Instruction::XAA,
    Instruction::STY, Instruction::STA, Instruction::STX, Instruction::SAX,
    Instruction::BCC, Instruction::STA, Instruction::STP, Instruction::AHX,
    Instruction::STY, Instruction::STA, Instruction::STX, Instruction::SAX,
    Instruction::TYA, Instruction::STA, Instruction::TXS, Instruction::TAS,
    Instruction::SHY, Instruction::STA, Instruction::SHX, Instruction::AHX,
    Instruction::LDY, Instruction::LDA, Instruction::LDX, Instruction::LAX,
    Instruction::LDY, Instruction::LDA, Instruction::LDX, Instruction::LAX,
    Instruction::TAY, Instruction::LDA, Instruction::TAX, Instruction::LAX,
    Instruction::LDY, Instruction::LDA, Instruction::LDX, Instruction::LAX,
    Instruction::BCS, Instruction::LDA, Instruction::STP, Instruction::LAX,
    Instruction::LDY, Instruction::LDA, Instruction::LDX, Instruction::LAX,
    Instruction::CLV, Instruction::LDA, Instruction::TSX, Instruction::LAS,
    Instruction::LDY, Instruction::LDA, Instruction::LDX, Instruction::LAX,
    Instruction::CPY, Instruction::CMP, Instruction::NOP, Instruction::DCP,
    Instruction::CPY, Instruction::CMP, Instruction::DEC, Instruction::DCP,
    Instruction::INY, Instruction::CMP, Instruction::DEX, Instruction::AXS,
    Instruction::CPY, Instruction::CMP, Instruction::DEC, Instruction::DCP,
    Instruction::BNE, Instruction::CMP, Instruction::STP, Instruction::DCP,
    Instruction::NOP, Instruction::CMP, Instruction::DEC, Instruction::DCP,
    Instruction::CLD, Instruction::CMP, Instruction::NOP, Instruction::DCP,
    Instruction::NOP, Instruction::CMP, Instruction::DEC, Instruction::DCP,
    Instruction::CPX, Instruction::SBC, Instruction::NOP, Instruction::ISC,
    Instruction::CPX, Instruction::SBC, Instruction::INC, Instruction::ISC,
    Instruction::INX, Instruction::SBC, Instruction::NOP, Instruction::SBC,
    Instruction::CPX, Instruction::SBC, Instruction::INC, Instruction::ISC,
    Instruction::BEQ, Instruction::SBC, Instruction::STP, Instruction::ISC,
    Instruction::NOP, Instruction::SBC, Instruction::INC, Instruction::ISC,
    Instruction::SED, Instruction::SBC, Instruction::NOP, Instruction::ISC,
    Instruction::NOP, Instruction::SBC, Instruction::INC, Instruction::ISC,
];

impl From<u8> for Instruction {
    fn from(opcode: u8) -> Self {
        INSTRUCTION_MAP[opcode as usize]
    }
}
